version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nix"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nix"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nix"
    directory: "/"
    target-branch: "release-25.05"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nix"
    directory: "/"
    target-branch: "release-25.11"
    schedule:
      interval: "weekly"
