queue_rules:
  - name: default
    merge_conditions:
      - check-success=buildbot/nix-build
    merge_method: squash

pull_request_rules:
  - name: auto-merge PRs updating lock files
    conditions:
      - base~=(main|develop|release-\d+\.\d+)
      - label~=merge-queue|dependencies
      - files~=\.*\.lock$
    actions:
      queue:
  - name: delete branches of closed PRs from an automation
    conditions:
      - base~=(main|develop|release-\d+\.\d+)
      - label~=merge-queue
      - closed
    actions:
      delete_head_branch:
