name: "AutoFirma"
url: "https://firmaelectronica.gob.es/Home/Descargas.html"
ssl_no_verify: true
filter:
  - xpath: //a
  - grep: "AutoFirma"
  - grep: "Linux"
  - xpath: //@href
---
name: "Configurador FNMT-RCM"
url: "https://www.sede.fnmt.gob.es/descargas/descarga-software/instalacion-software-generacion-de-claves"
ssl_no_verify: true
filter:
  - xpath: //a
  - grep: "Configurador"
  - grep: "FNMT-RCM"
  - grep: "Linux"
  - xpath: //@href
---
name: "DNIeRemote"
url: "https://www.dnielectronico.es/PortalDNIe/PRF1_Cons02.action?pag=REF_1015&id_menu=67"
ssl_no_verify: true
filter:
  - xpath: //a
  - grep: "DNIe"
  - grep: "Remote"
  - grep: "Linux"
  - xpath: //@href
---